import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/services/sales_management_service.dart';
import '../../domain/entities/sales_invoice_entity.dart';
import '../../domain/entities/payment_receipt_entity.dart';
import 'booking_wizard_state.dart';

/// Booking & Sales Wizard Cubit
///
/// Multi-step workflow: Customer -> Vehicle -> On-Road Pricing -> Payments -> Final GST Tax Invoice.
class BookingWizardCubit extends Cubit<BookingWizardState> {
  final SalesManagementService _salesService;

  BookingWizardCubit({SalesManagementService? salesService})
      : _salesService = salesService ?? SalesManagementService.instance,
        super(const BookingWizardState());

  void nextStep() {
    if (state.currentStep < 4) {
      emit(state.copyWith(currentStep: state.currentStep + 1));
    }
  }

  void previousStep() {
    if (state.currentStep > 0) {
      emit(state.copyWith(currentStep: state.currentStep - 1));
    }
  }

  void goToStep(int step) {
    if (step >= 0 && step <= 4) {
      emit(state.copyWith(currentStep: step));
    }
  }

  void setShowroomId(String showroomId) {
    emit(state.copyWith(selectedShowroomId: showroomId));
  }

  void setCustomer({
    String? id,
    required String name,
    required String mobile,
  }) {
    emit(state.copyWith(
      selectedCustomerId: id,
      customerName: name,
      customerMobile: mobile,
    ));
  }

  void setVehicle({
    required String modelId,
    required String modelName,
    required String variantId,
    required String variantName,
    required String colorId,
    required String colorName,
    required String colorHex,
    required double exShowroomPrice,
    required bool isEv,
    String? vin,
  }) {
    final gst = isEv ? 5.0 : 28.0;
    // Standard approximate Indian dealership estimates
    final rto = isEv ? 2500.0 : (exShowroomPrice * 0.10); // RTO ~10% for ICE, nominal for EV
    final insurance = isEv ? (exShowroomPrice * 0.055) : (exShowroomPrice * 0.06); // 1+5 yr comprehensive

    emit(state.copyWith(
      selectedModelId: modelId,
      selectedModelName: modelName,
      selectedVariantId: variantId,
      selectedVariantName: variantName,
      selectedColorId: colorId,
      selectedColorName: colorName,
      selectedColorHex: colorHex,
      exShowroomPrice: exShowroomPrice,
      gstRate: gst,
      isEv: isEv,
      selectedVin: vin,
      rtoCharges: rto.roundToDouble(),
      insuranceCharges: insurance.roundToDouble(),
      accessoriesTotal: 3500.0,
      extendedWarrantyAmount: 2500.0,
      fastagCharges: 500.0,
    ));
  }

  void updatePricing({
    double? exShowroomPrice,
    double? discountAmount,
    double? rtoCharges,
    double? insuranceCharges,
    double? accessoriesTotal,
    double? extendedWarrantyAmount,
    double? fastagCharges,
    double? hypothecationCharges,
  }) {
    emit(state.copyWith(
      exShowroomPrice: exShowroomPrice,
      discountAmount: discountAmount,
      rtoCharges: rtoCharges,
      insuranceCharges: insuranceCharges,
      accessoriesTotal: accessoriesTotal,
      extendedWarrantyAmount: extendedWarrantyAmount,
      fastagCharges: fastagCharges,
      hypothecationCharges: hypothecationCharges,
    ));
  }

  void updatePayment({
    double? bookingAdvance,
    double? financeAmount,
    String? financeBank,
    double? exchangeAllowance,
    double? downPayment,
    String? paymentMode,
  }) {
    emit(state.copyWith(
      bookingAdvanceAdjusted: bookingAdvance,
      financeAmount: financeAmount,
      financeBank: financeBank,
      exchangeAllowance: exchangeAllowance,
      downPaymentPaid: downPayment,
      paymentMode: paymentMode,
    ));
  }

  /// Generate the final GST Tax Invoice
  Future<bool> generateInvoice() async {
    emit(state.copyWith(isSaving: true, error: null));
    try {
      final vin = state.selectedVin ?? 'VIN-${DateTime.now().millisecondsSinceEpoch.toString().substring(5)}';

      final invoice = SalesInvoiceEntity(
        id: '',
        showroomId: state.selectedShowroomId ?? 'showroom-mumbai-main',
        customerId: state.selectedCustomerId ?? 'cust-001',
        invoiceNumber: '', // Auto-generated by service
        invoiceDate: DateTime.now(),
        variantId: state.selectedVariantId!,
        colorId: state.selectedColorId!,
        vin: vin,
        hsnCode: '8711',
        gstRate: state.gstRate,
        isInterstate: false,
        exShowroomPrice: state.exShowroomPrice,
        discountAmount: state.discountAmount,
        taxableAmount: state.taxableAmount,
        cgstAmount: state.cgstAmount,
        sgstAmount: state.sgstAmount,
        rtoCharges: state.rtoCharges,
        insuranceCharges: state.insuranceCharges,
        accessoriesTotal: state.accessoriesTotal,
        extendedWarrantyAmount: state.extendedWarrantyAmount,
        fastagCharges: state.fastagCharges,
        hypothecationCharges: state.hypothecationCharges,
        totalOnRoadPrice: state.totalOnRoadPrice,
        bookingAdvanceAdjusted: state.bookingAdvanceAdjusted,
        financeAmount: state.financeAmount,
        financeBank: state.financeBank,
        exchangeAllowance: state.exchangeAllowance,
        amountPaid: state.totalPaid,
        balanceAmount: state.balanceAmount,
        paymentStatus: state.balanceAmount <= 0 ? 'paid' : 'partial',
        status: 'issued',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        customerName: state.customerName,
        customerMobile: state.customerMobile,
        modelName: state.selectedModelName,
        variantName: state.selectedVariantName,
        colorName: state.selectedColorName,
        showroomName: 'Selected Showroom',
      );

      final createdInvoice = await _salesService.createInvoice(invoice);

      // Record payment receipt if down payment or advance was collected
      if (state.downPaymentPaid > 0) {
        await _salesService.recordPaymentReceipt(PaymentReceiptEntity(
          id: '',
          showroomId: createdInvoice.showroomId,
          customerId: createdInvoice.customerId,
          invoiceId: createdInvoice.id,
          receiptNumber: '',
          receiptDate: DateTime.now(),
          amount: state.downPaymentPaid,
          paymentMode: state.paymentMode,
          paymentReference: 'WIZARD-DOWNPAY-${DateTime.now().millisecondsSinceEpoch}',
          createdAt: DateTime.now(),
          customerName: state.customerName,
        ));
      }

      emit(state.copyWith(
        isSaving: false,
        savedInvoice: createdInvoice,
      ));
      return true;
    } catch (e) {
      emit(state.copyWith(isSaving: false, error: e.toString()));
      return false;
    }
  }
}
