import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/services/customer_management_service.dart';
import '../../domain/entities/customer_entity.dart';
import 'customer_form_state.dart';

/// Customer Form Cubit
///
/// Manages create/edit customer form with field-level updates and validation.
class CustomerFormCubit extends Cubit<CustomerFormState> {
  final CustomerManagementService _service;

  CustomerFormCubit({CustomerManagementService? service})
      : _service = service ?? CustomerManagementService.instance,
        super(const CustomerFormState());

  /// Initialize for editing an existing customer
  Future<void> loadForEdit(String customerId) async {
    emit(state.copyWith(isLoading: true, isEditMode: true, editCustomerId: customerId));
    try {
      final customer = await _service.fetchCustomerById(customerId);
      if (customer != null) {
        emit(state.copyWith(
          isLoading: false,
          firstName: customer.firstName,
          lastName: customer.lastName,
          mobilePrimary: customer.mobilePrimary,
          mobileSecondary: customer.mobileSecondary,
          email: customer.email,
          dateOfBirth: customer.dateOfBirth,
          gender: customer.gender,
          addressLine1: customer.addressLine1,
          addressLine2: customer.addressLine2,
          city: customer.city,
          state: customer.state,
          pinCode: customer.pinCode,
          landmark: customer.landmark,
          customerType: customer.customerType,
          source: customer.source,
          preferredContactMethod: customer.preferredContactMethod,
          notes: customer.notes,
          selectedShowroomId: customer.showroomId,
        ));
      } else {
        emit(state.copyWith(isLoading: false, error: 'Customer not found'));
      }
    } catch (e) {
      emit(state.copyWith(isLoading: false, error: e.toString()));
    }
  }

  // ─── Field Updaters ───
  void updateFirstName(String value) => emit(state.copyWith(firstName: value));
  void updateLastName(String value) => emit(state.copyWith(lastName: value));
  void updateMobilePrimary(String value) => emit(state.copyWith(mobilePrimary: value));
  void updateMobileSecondary(String value) => emit(state.copyWith(mobileSecondary: value));
  void updateEmail(String value) => emit(state.copyWith(email: value));
  void updateDateOfBirth(DateTime value) => emit(state.copyWith(dateOfBirth: value));
  void updateGender(String value) => emit(state.copyWith(gender: value));
  void updateAddressLine1(String value) => emit(state.copyWith(addressLine1: value));
  void updateAddressLine2(String value) => emit(state.copyWith(addressLine2: value));
  void updateCity(String value) => emit(state.copyWith(city: value));
  void updateState(String value) => emit(state.copyWith(state: value));
  void updatePinCode(String value) => emit(state.copyWith(pinCode: value));
  void updateLandmark(String value) => emit(state.copyWith(landmark: value));
  void updateCustomerType(String value) => emit(state.copyWith(customerType: value));
  void updateSource(String value) => emit(state.copyWith(source: value));
  void updatePreferredContact(String value) => emit(state.copyWith(preferredContactMethod: value));
  void updateNotes(String value) => emit(state.copyWith(notes: value));
  void updateShowroomId(String value) => emit(state.copyWith(selectedShowroomId: value));

  /// Validate and save the customer
  Future<void> saveCustomer() async {
    // Validate required fields
    if (state.firstName.trim().isEmpty) {
      emit(state.copyWith(error: 'First name is required'));
      return;
    }
    if (state.lastName.trim().isEmpty) {
      emit(state.copyWith(error: 'Last name is required'));
      return;
    }
    if (state.mobilePrimary.trim().length != 10) {
      emit(state.copyWith(error: 'Mobile number must be 10 digits'));
      return;
    }
    if (state.selectedShowroomId == null || state.selectedShowroomId!.isEmpty) {
      emit(state.copyWith(error: 'Please select a showroom'));
      return;
    }

    emit(state.copyWith(isSaving: true));
    try {
      final customer = CustomerEntity(
        id: state.editCustomerId ?? '',
        showroomId: state.selectedShowroomId!,
        customerNumber: '', // Auto-generated by service
        firstName: state.firstName.trim(),
        lastName: state.lastName.trim(),
        mobilePrimary: state.mobilePrimary.trim(),
        mobileSecondary: state.mobileSecondary,
        email: state.email,
        dateOfBirth: state.dateOfBirth,
        gender: state.gender,
        addressLine1: state.addressLine1,
        addressLine2: state.addressLine2,
        city: state.city,
        state: state.state,
        pinCode: state.pinCode,
        landmark: state.landmark,
        customerType: state.customerType,
        source: state.source,
        preferredContactMethod: state.preferredContactMethod,
        notes: state.notes,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      if (state.isEditMode && state.editCustomerId != null) {
        await _service.updateCustomer(state.editCustomerId!, customer);
      } else {
        await _service.createCustomer(customer);
      }

      emit(state.copyWith(isSaving: false, isSaved: true));
    } catch (e) {
      emit(state.copyWith(isSaving: false, error: e.toString()));
    }
  }
}
